env:
  browser: true
  es2021: true
  node: true
extends: 'plugin:react/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - '@jambit/typed-redux-saga'
settings:
  react:
    createClass: createReactClass # Regex for Component Factory to use, default to "createReactClass"
    pragma: React
    fragment: Fragment # Fragment to use (may be a property of <pragma>), default to "Fragment"
    version: detect
    flowVersion: '0.53'
  propWrapperFunctions:
    # The names of any function used to wrap propTypes, e.g. `forbidExtraProps`. If this isn't set, any propTypes wrapped in a function will be skipped.
    - forbidExtraProps
    - property: freeze
      object: Object
    - property: myFavoriteWrapper
  linkComponents:
    # Components used as alternatives to <a> for linking, eg. <Link to={ url } />
    - Hyperlink
    - name: Link
      linkAttribute: to
rules:
  react/prop-types: off
  react/no-unescaped-entities: ["error", {"forbid": [">", "}"]}]
  indent: ["error", 4, {"SwitchCase": 1}]
overrides:
  -
    files:
      - "./**/*.ts"
      - "./**/*.tsx"
    excludedFiles:
      - "./**/*.spec.ts"
    rules:
      "@jambit/typed-redux-saga/use-typed-effects":
        - error
      "@jambit/typed-redux-saga/delegate-effects": error
