version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run:
          name: "Setup Node auth token"
          command: |
            echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
            echo "@france-ioi:registry=https://npm.pkg.github.com/" >> ~/.npmrc
            echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> ~/.npmrc
      - run:
          name: "Fetch submodules"
          command: git submodule update --init
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: "Copy config"
          command: cp config.json.template config.json
      - run:
          name: "Build Codecast lib"
          command: yarn build-lib
      - persist_to_workspace:
          root: .
          paths:
            - 'build'
  commit:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Clone bebras-modules"
          command: git clone https://${GITHUB_USERNAME}:${NODE_AUTH_TOKEN}@github.com/France-ioi/bebras-modules.git
      - run:
          name: "Copy new files"
          command: |
            ls -asl build
            cp build/index.js bebras-modules/ext/codecast/7.5/index.js
            cp build/index.css bebras-modules/ext/codecast/7.5/index.css
            cp build/index.worker.worker.js bebras-modules/ext/codecast/7.5/index.worker.worker.js
      - run:
          name: "Commit changes"
          command: |
            cd bebras-modules
            git config credential.helper cache
            git config user.email "admin@france-ioi.org"
            git config user.name "Deployment"
            git add .
            git commit --allow-empty -m "Upgrade Codecast 7.4 ($CIRCLE_SHA1)"
      - run:
          name: "Push changes"
          command: |
            cd bebras-modules
            git push -u origin master

workflows:
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only: lib
      - commit:
          requires:
            - build
          filters:
            branches:
              only: lib
