version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run:
          command: |
            echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
            echo "@france-ioi:registry=https://npm.pkg.github.com/" >> ~/.npmrc
            echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> ~/.npmrc
          name: "Setup Node auth token"
      - run:
          command: git submodule update --init
          name: Fetch submodules
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: cp config.json.template config.json
          name: Copy config
      - run:
          command: yarn build-lib
          name: Build Codecast lib
      - persist_to_workspace:
          root: .
          paths:
            - 'build'
  commit:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Commit changes"
          command: |
            ls -asl build
            git clone git@github.com:France-ioi/bebras-modules.git
            cd bebras-modules
            git config credential.helper cache
            git config user.email "admin@france-ioi.org"
            git config user.name "Deployment"
            cp ../build/index.js ext/codecast/7.4/index.js
            cp ../build/index.css ext/codecast/7.4/index.css
            cp ../index.worker.worker.js ext/codecast/7.4/index.worker.worker.js
            git commit --allow-empty -m "Upgrade Codecast 7.4"

workflows:
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only: lib
      - commit:
          requires:
            - build
          filters:
            branches:
              only: lib
